steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
  - -c
  - |
    gcloud run deploy creator-crawl-backend \
      --source . \
      --region europe-west1 \
      --platform managed \
      --allow-unauthenticated

serviceAccount: 'projects/project-ea15e69f-4168-435a-966/serviceAccounts/748311918336-compute@project-ea15e69f-4168-435a-966.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
  substitutionOption: ALLOW_LOOSE
